-- MySQL Script generated by MySQL Workbench
-- 05/03/16 02:45:17
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema tech_db
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `tech_db` ;

-- -----------------------------------------------------
-- Schema tech_db
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `tech_db` DEFAULT CHARACTER SET utf8 ;
USE `tech_db` ;

-- -----------------------------------------------------
-- Table `tech_db`.`forum`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `tech_db`.`forum` ;

CREATE TABLE IF NOT EXISTS `tech_db`.`forum` (
  `idForum` VARCHAR(255) NOT NULL,
  `name` VARCHAR(255) NOT NULL,
  `shortname` VARCHAR(255) NOT NULL,
  `userCreatedId` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`idForum`))
ENGINE = InnoDB;

CREATE UNIQUE INDEX `id_UNIQUE` ON `tech_db`.`forum` (`idForum` ASC);

CREATE UNIQUE INDEX `shortname_UNIQUE` ON `tech_db`.`forum` (`shortname` ASC);

CREATE UNIQUE INDEX `name_UNIQUE` ON `tech_db`.`forum` (`name` ASC);


-- -----------------------------------------------------
-- Table `tech_db`.`user`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `tech_db`.`user` ;

CREATE TABLE IF NOT EXISTS `tech_db`.`user` (
  `idUser` VARCHAR(50) NOT NULL,
  `name` VARCHAR(255) NULL,
  `username` VARCHAR(255) NULL,
  `about` MEDIUMTEXT NULL,
  `isAnonymous` TINYINT(1) NOT NULL DEFAULT 0,
  PRIMARY KEY (`idUser`))
ENGINE = InnoDB;

CREATE UNIQUE INDEX `id_UNIQUE` ON `tech_db`.`user` (`idUser` ASC);


-- -----------------------------------------------------
-- Table `tech_db`.`thread`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `tech_db`.`thread` ;

CREATE TABLE IF NOT EXISTS `tech_db`.`thread` (
  `idThread` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `forumParentId` VARCHAR(255) NOT NULL,
  `userCreatedId` VARCHAR(50) NOT NULL,
  `title` VARCHAR(255) NOT NULL,
  `slug` VARCHAR(255) NOT NULL,
  `dateU` VARCHAR(20) NOT NULL,
  `message` MEDIUMTEXT NOT NULL,
  `isClosed` TINYINT(1) NOT NULL DEFAULT 0,
  `isDeleted` TINYINT(1) NOT NULL DEFAULT 0,
  `likes` INT UNSIGNED NOT NULL DEFAULT 0,
  `dislikes` INT UNSIGNED NOT NULL DEFAULT 0,
  PRIMARY KEY (`idThread`))
ENGINE = InnoDB;

CREATE UNIQUE INDEX `id_UNIQUE` ON `tech_db`.`thread` (`idThread` ASC);

CREATE INDEX `iii2` ON `tech_db`.`thread` (`forumParentId` ASC);

CREATE INDEX `iii3` ON `tech_db`.`thread` (`userCreatedId` ASC);

CREATE INDEX `datethread` ON `tech_db`.`thread` (`dateU` ASC);


-- -----------------------------------------------------
-- Table `tech_db`.`post`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `tech_db`.`post` ;

CREATE TABLE IF NOT EXISTS `tech_db`.`post` (
  `idPost` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `postParentId` INT NULL,
  `threadParentId` INT UNSIGNED NOT NULL,
  `userCreatedId` VARCHAR(50) NOT NULL,
  `forumParentId` VARCHAR(255) NOT NULL,
  `postPath` VARCHAR(255) NULL,
  `dateU` VARCHAR(20) NOT NULL,
  `message` MEDIUMTEXT NOT NULL,
  `isApproved` TINYINT(1) NOT NULL DEFAULT 0,
  `isDeleted` TINYINT(1) NOT NULL DEFAULT 0,
  `isEdited` TINYINT(1) NOT NULL DEFAULT 0,
  `isHighlighted` TINYINT(1) NOT NULL DEFAULT 0,
  `isSpam` TINYINT(1) NOT NULL DEFAULT 0,
  `likes` INT UNSIGNED NOT NULL DEFAULT 0,
  `dislikes` INT UNSIGNED NOT NULL DEFAULT 0,
  `levelnum` INT UNSIGNED NULL,
  `level` INT UNSIGNED NULL DEFAULT 0,
  PRIMARY KEY (`idPost`))
ENGINE = InnoDB;

CREATE UNIQUE INDEX `idPost_UNIQUE` ON `tech_db`.`post` (`idPost` ASC);

CREATE INDEX `ii2` ON `tech_db`.`post` (`postParentId` ASC);

CREATE INDEX `ii3` ON `tech_db`.`post` (`threadParentId` ASC);

CREATE INDEX `ii4` ON `tech_db`.`post` (`userCreatedId` ASC);

CREATE INDEX `ii5` ON `tech_db`.`post` (`forumParentId` ASC);

CREATE INDEX `iipath` ON `tech_db`.`post` (`postPath` ASC);

CREATE INDEX `levelidx` ON `tech_db`.`post` (`level` ASC);

CREATE INDEX `levelnumidx` ON `tech_db`.`post` (`levelnum` ASC);

CREATE INDEX `datepost` ON `tech_db`.`post` (`dateU` ASC);


-- -----------------------------------------------------
-- Table `tech_db`.`follow`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `tech_db`.`follow` ;

CREATE TABLE IF NOT EXISTS `tech_db`.`follow` (
  `ktoId` VARCHAR(50) NOT NULL,
  `kogoId` VARCHAR(50) NOT NULL)
ENGINE = InnoDB;

CREATE INDEX `idx1` ON `tech_db`.`follow` (`ktoId` ASC);

CREATE INDEX `idx2` ON `tech_db`.`follow` (`kogoId` ASC);


-- -----------------------------------------------------
-- Table `tech_db`.`subscribe`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `tech_db`.`subscribe` ;

CREATE TABLE IF NOT EXISTS `tech_db`.`subscribe` (
  `userId` VARCHAR(50) NOT NULL,
  `threadId` INT UNSIGNED NOT NULL)
ENGINE = InnoDB;

CREATE INDEX `idxs1` ON `tech_db`.`subscribe` (`userId` ASC);

USE `tech_db`;

DELIMITER $$

USE `tech_db`$$
DROP TRIGGER IF EXISTS `tech_db`.`thread_AFTER_UPDATE` $$
USE `tech_db`$$
CREATE DEFINER = CURRENT_USER TRIGGER `tech_db`.`thread_AFTER_UPDATE` AFTER UPDATE ON `thread` FOR EACH ROW
BEGIN

END
$$


DELIMITER ;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
