-- MySQL Script generated by MySQL Workbench
-- 04/10/16 12:11:27
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema tech_db
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `tech_db` ;

-- -----------------------------------------------------
-- Schema tech_db
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `tech_db` DEFAULT CHARACTER SET utf8 ;
USE `tech_db` ;

-- -----------------------------------------------------
-- Table `tech_db`.`user`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `tech_db`.`user` ;

CREATE TABLE IF NOT EXISTS `tech_db`.`user` (
  `idUser` VARCHAR(50) NOT NULL,
  `name` VARCHAR(255) NULL,
  `username` VARCHAR(255) NULL,
  `about` MEDIUMTEXT NULL,
  `isAnonymous` TINYINT(1) NOT NULL DEFAULT 0,
  PRIMARY KEY (`idUser`))
ENGINE = InnoDB;

CREATE UNIQUE INDEX `id_UNIQUE` ON `tech_db`.`user` (`idUser` ASC);


-- -----------------------------------------------------
-- Table `tech_db`.`forum`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `tech_db`.`forum` ;

CREATE TABLE IF NOT EXISTS `tech_db`.`forum` (
  `idForum` VARCHAR(255) NOT NULL,
  `name` VARCHAR(255) NOT NULL,
  `shortname` VARCHAR(255) NOT NULL,
  `userCreatedId` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`idForum`),
  CONSTRAINT `fk_forum_user`
    FOREIGN KEY (`userCreatedId`)
    REFERENCES `tech_db`.`user` (`idUser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE UNIQUE INDEX `id_UNIQUE` ON `tech_db`.`forum` (`idForum` ASC);

CREATE UNIQUE INDEX `shortname_UNIQUE` ON `tech_db`.`forum` (`shortname` ASC);

CREATE UNIQUE INDEX `name_UNIQUE` ON `tech_db`.`forum` (`name` ASC);

CREATE INDEX `fk_forum_user_idx` ON `tech_db`.`forum` (`userCreatedId` ASC);


-- -----------------------------------------------------
-- Table `tech_db`.`thread`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `tech_db`.`thread` ;

CREATE TABLE IF NOT EXISTS `tech_db`.`thread` (
  `idThread` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `forumParentId` VARCHAR(255) NOT NULL,
  `userCreatedId` VARCHAR(50) NOT NULL,
  `title` VARCHAR(255) NOT NULL,
  `slug` VARCHAR(255) NOT NULL,
  `dateU` VARCHAR(20) NOT NULL,
  `message` MEDIUMTEXT NOT NULL,
  `isClosed` TINYINT(1) NOT NULL DEFAULT 0,
  `isDeleted` TINYINT(1) NOT NULL DEFAULT 0,
  `likes` INT UNSIGNED NOT NULL DEFAULT 0,
  `dislikes` INT UNSIGNED NOT NULL DEFAULT 0,
  PRIMARY KEY (`idThread`),
  CONSTRAINT `fk_thread_user`
    FOREIGN KEY (`userCreatedId`)
    REFERENCES `tech_db`.`user` (`idUser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_thread_forum`
    FOREIGN KEY (`forumParentId`)
    REFERENCES `tech_db`.`forum` (`idForum`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE UNIQUE INDEX `id_UNIQUE` ON `tech_db`.`thread` (`idThread` ASC);

CREATE INDEX `fk_thread_user_idx` ON `tech_db`.`thread` (`userCreatedId` ASC);

CREATE INDEX `fk_thread_forum_idx` ON `tech_db`.`thread` (`forumParentId` ASC);


-- -----------------------------------------------------
-- Table `tech_db`.`post`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `tech_db`.`post` ;

CREATE TABLE IF NOT EXISTS `tech_db`.`post` (
  `idPost` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `postParentId` INT NULL,
  `threadParentId` INT UNSIGNED NOT NULL,
  `userCreatedId` VARCHAR(50) NOT NULL,
  `forumParentId` VARCHAR(255) NOT NULL,
  `postPath` VARCHAR(255) NULL,
  `dateU` VARCHAR(20) NOT NULL,
  `message` MEDIUMTEXT NOT NULL,
  `isApproved` TINYINT(1) NOT NULL DEFAULT 0,
  `isDeleted` TINYINT(1) NOT NULL DEFAULT 0,
  `isEdited` TINYINT(1) NOT NULL DEFAULT 0,
  `isHighlighted` TINYINT(1) NOT NULL DEFAULT 0,
  `isSpam` TINYINT(1) NOT NULL DEFAULT 0,
  `likes` INT UNSIGNED NOT NULL DEFAULT 0,
  `dislikes` INT UNSIGNED NOT NULL DEFAULT 0,
  `levelnum` INT UNSIGNED NULL,
  `level` INT UNSIGNED NULL DEFAULT 0,
  PRIMARY KEY (`idPost`),
  CONSTRAINT `fk_post_user`
    FOREIGN KEY (`userCreatedId`)
    REFERENCES `tech_db`.`user` (`idUser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_post_forum`
    FOREIGN KEY (`forumParentId`)
    REFERENCES `tech_db`.`forum` (`idForum`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_post_thread`
    FOREIGN KEY (`threadParentId`)
    REFERENCES `tech_db`.`thread` (`idThread`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE UNIQUE INDEX `idPost_UNIQUE` ON `tech_db`.`post` (`idPost` ASC);

CREATE INDEX `fk_post_user_idx` ON `tech_db`.`post` (`userCreatedId` ASC);

CREATE INDEX `fk_post_forum_idx` ON `tech_db`.`post` (`forumParentId` ASC);

CREATE INDEX `fk_post_thread_idx` ON `tech_db`.`post` (`threadParentId` ASC);


-- -----------------------------------------------------
-- Table `tech_db`.`follow`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `tech_db`.`follow` ;

CREATE TABLE IF NOT EXISTS `tech_db`.`follow` (
  `ktoId` VARCHAR(50) NOT NULL,
  `kogoId` VARCHAR(50) NOT NULL,
  CONSTRAINT `fk_follow_id1`
    FOREIGN KEY (`ktoId`)
    REFERENCES `tech_db`.`user` (`idUser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_follow_id2`
    FOREIGN KEY (`kogoId`)
    REFERENCES `tech_db`.`user` (`idUser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_follow_id1_idx` ON `tech_db`.`follow` (`ktoId` ASC);

CREATE INDEX `fk_follow_id2_idx` ON `tech_db`.`follow` (`kogoId` ASC);


-- -----------------------------------------------------
-- Table `tech_db`.`subscribe`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `tech_db`.`subscribe` ;

CREATE TABLE IF NOT EXISTS `tech_db`.`subscribe` (
  `userId` VARCHAR(50) NOT NULL,
  `threadId` INT UNSIGNED NOT NULL,
  CONSTRAINT `fk_user_subscribe`
    FOREIGN KEY (`userId`)
    REFERENCES `tech_db`.`user` (`idUser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_thread_subscribe`
    FOREIGN KEY (`threadId`)
    REFERENCES `tech_db`.`thread` (`idThread`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_user_subscribe_idx` ON `tech_db`.`subscribe` (`userId` ASC);

CREATE INDEX `fk_thread_subscribe_idx` ON `tech_db`.`subscribe` (`threadId` ASC);


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
